In [6]:
import numpy as np
import pandas as pd 

# importing data

In [8]:
Sales_data = np.loadtxt("sales_data.csv", delimiter=",", skiprows=1,dtype=int)
print(Sales_data)

[[     0 185503 198442 245134 294712]
 [     1 208539 204388 199262 266072]
 [     2 180069 225999 214299 218394]
 ...
 [ 19998 172480 196970 244006 266135]
 [ 19999 177589 195561 247882 316233]
 [ 20000 132575 181985 173262 194274]]


In [10]:
print(Sales_data[:2])

[[     0 185503 198442 245134 294712]
 [     1 208539 204388 199262 266072]]


# Sum of the data


In [12]:
# axis = 0  sum top to bottom in a column
print(np.sum(Sales_data,axis=0))  
#  axis = 1 sum left to right in a row 
print(np.sum(Sales_data,axis=1))


[ 200010000 3998950298 4305103653 4751886406 5355849495]
[923791 878262 838763 ... 899589 957264 702096]


In [ ]:
# more operation using sum  and slicing

print(np.sum(Sales_data[0:101,1:],axis=0)) 
# above sum the columns top to bottom starting from row 0 to 100 and columns from 1 to last column 

[20143608 21897214 23701328 26639538]


# Minimum and Maximum of the data

In [ ]:
# minimum sales amongst the restraunt (all rows and all colms except the index) quarter-wise

minSaleAmongstRestraunt = np.min(Sales_data[:,1:],axis=0)

print(minSaleAmongstRestraunt)

[100002  80794  72218  69688]


In [ ]:
# minimum sales in the quarters in restraunt

In [18]:
minSaleAmongstRestraunt = np.min(Sales_data[:,1:],axis=1)

print(minSaleAmongstRestraunt)

[185503 199262 180069 ... 172480 177589 132575]


# np.mean(arr[],axis=0 or 1 ) for average and np.cumsum(arr[],axis=0 or 1) for cummulative sum