In [1]:
import numpy as np

In [6]:
a1 =  np.arange(12).reshape(3,4)
print(a1,"\ndimension of the array is: ",a1.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
dimension of the array is:  2


In [7]:
print(a1[::2,::3])

[[ 0  3]
 [ 8 11]]


In [11]:
print(a1[1,::3])

[4 7]
